name: Build and Deploy React App to Azure App Service

on:
  push:
    branches:
      - main  # أو master إذا كنت تستخدم فرع ثاني
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd src/webapp
          npm install

      - name: Build the app
        run: |
          cd src/webapp
          npm run build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-react-on-azure   # ← استبدله باسم App Service في Azure
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: src/webapp/build
